title: Soamya Agrawal # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer
  <br><br>
  <a href="mailto:soamyaagrawal@gmail.com">soamyaagrawal@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/soamya-agrawal/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
